# Site settings
title: PEBBLE
description: Physics + Engineering + Biology + Biotechnology + Learning + Experience
email: your-email@example.com
baseurl: ""
url: "https://pebble-biofusion.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
  - _tools
  - README.md
  - LICENSE

# Collections
collections:
  projects:
    output: true
    permalink: /workshop/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
